function f(t){
    if(t==1){
        document.getElementById("exp").innerHTML = "0";
    }
    if(t==2){
        let s=document.getElementById("exp").innerHTML;
        document.getElementById("exp").innerHTML=s.slice(0,-1);
        if(document.getElementById("exp").innerHTML==""){
            document.getElementById("exp").innerHTML="0";
        }
    }
    if(t==3){
        s=document.getElementById("exp").innerHTML;
        j=-1;
        for(i=s.length-1;i>=0;i--){
            if(s[i]=='+'||s[i]=='-'||s[i]=='*'||s[i]=='/'){
                j=i;
                break;
            }
        }
        if(j==-1){
            document.getElementById("exp").innerHTML=-1*parseFloat(s);
        }
        else{
            s=s.slice(0,j+1)+'(-'+s.slice(j+1)+')';
            document.getElementById("exp").innerHTML=s;
        }
       
    }
    if(t==4){
        s=document.getElementById("exp").innerHTML;
        if(s.charAt(s.length-1)=='+'||s.charAt(s.length-1)=='-'||s.charAt(s.length-1)=='/'||s.charAt(s.length-1)=='*'){
            return
        }
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'/';    

    }
    if(t==5){
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'7';        
    }
    if(t==6){        
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'8';        
    }
    if(t==7){        
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'9';        
    }
    if(t==8){  
        s=document.getElementById("exp").innerHTML;
        if(s.charAt(s.length-1)=='+'||s.charAt(s.length-1)=='-'||s.charAt(s.length-1)=='/'||s.charAt(s.length-1)=='*'){
            return
        }      
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'*';        
    }
    if(t==9){        
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'4';        
    }
    if(t==10){
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'5';          
    }
    if(t==11){
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'6';         
    }
    if(t==12){
        s=document.getElementById("exp").innerHTML;
        if(s.charAt(s.length-1)=='+'||s.charAt(s.length-1)=='-'||s.charAt(s.length-1)=='/'||s.charAt(s.length-1)=='*'){
            return
        }
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'-';   
        
    }
    if(t==13){
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'1';   
    }
    if(t==14){
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'2';   
    }
    if(t==15){
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'3';   
    }
    if(t==16){
        s=document.getElementById("exp").innerHTML;
        if(s.charAt(s.length-1)=='+'||s.charAt(s.length-1)=='-'||s.charAt(s.length-1)=='/'||s.charAt(s.length-1)=='*'){
            return
        }
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'+';   
    }
    if(t==17){
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'00';        
        
    }
    if(t==18){
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'0';        
    }
    if(t==19){
        s=document.getElementById("exp").innerHTML;
        for(i=s.length-1;i>=0;i--){
            if(s[i]=='+'||s[i]=='-'||s[i]=='*'||s[i]=='/'){
                break;
            }
            if(s[i]=='.'){
                return;
            }
        }
        document.getElementById("exp").innerHTML=document.getElementById("exp").innerHTML+'.';  


    }
    if(t==20){
        document.getElementById("exp").innerHTML=eval(document.getElementById("exp").innerHTML);        
    }
}
